### ISSUE TITLE
Parse metadata for keyword models

### ISSUE THREAD

**Issue by space-pope** [spokestack/spokestack-python#38]
A `metadata.json` file will be distributed alongside keyword models, and it will need to be parsed in order to configure the keyword recognizer with appropriate classes. The metadata format is expected to be:

```json
{
  "name": "model-name",
  "type": "keyword",
  "classes": [
    {
      "name": "class-name",
      "utterances": [
        {
          "id": "utterance-id",
          "text": "utterance text"
        }
      ]
    }
  ]
}
```

The keyword recognizer is interested in the values in `classes[].name`.

**Comment by brentspell** [comment]
We don't want the core keyword recognizer reading json files. This can be added to an analogue of https://github.com/spokestack/spokestack-android/blob/master/src/main/java/io/spokestack/spokestack/Spokestack.java if we ever need one in python.
